apiVersion: v1
kind: Service
metadata:
  name: vps-portal-backend
  namespace: ${NAMESPACE}
  labels:
    app: vps-portal-backend
    color: blue
spec:
  selector:
    app: vps-portal-backend
    color: blue
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None