apiVersion: v1
kind: Service
metadata:
  name: vps-portal-frontend
  namespace: ${NAMESPACE}
  labels:
    app: vps-portal-frontend
    color: blue
spec:
  selector:
    app: vps-portal-frontend
    color: blue
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None